### ISSUE TITLE
Generation of view outside of public

### ISSUE THREAD

**Issue by jamesy829** [scenic-views/scenic#187]
When I generate a view that is not in public schema, it will be generated incorrectly.

Steps to reproduce:

1. Executing the command `create_view "schema.table_names", --materialized`, it generates a migration of the class `CreateSchematableNames` and a SQL file `schema_table_names_v01.sql`
2. When migration is executed, it will complain  uninitialized constant `CreateSchemaTableNames`
3. If you change to that class, it complains `No such file or directory @ rb_sysopen - /home/james/code/twitter-crawler/db/views/twitter.users_uks_v01.sql`

Found similar issue (https://github.com/thoughtbot/scenic/issues/95) and the resolution was merged into master but something may have changed the behaviour (https://github.com/thoughtbot/scenic/pull/124) (https://github.com/thoughtbot/scenic/issues/125)

Will do more investigation but the workaround was to rename the class and sql file.

**Comment by magicalbanana** [comment]
Any updates on this?

**Comment by derekprior** [comment]
@magicalbanana I see now that this is the issue you were trying to fix in #255. An update on this is that I'm not going to fix it myself because I don't have this problem, but I would certainly merge a clean PR that is accompanied with a test case (probably in one of the generator specs).

**Comment by derekprior** [comment]
I believe this was addressed by #282
