### ISSUE TITLE
RFC: Scenic 2.0

### ISSUE THREAD

**Issue by derekprior** [scenic-views/scenic#201]
Plans for Scenic 2.0 were discussed at the latest [Scenic core team meeting](https://twitter.com/scenicgem). Since _some_ members (*cough* @calebthompson *cough*) of the team were on their fourth or fifth drink of the evening, I thought it would be worth opening an issue to nail down our final plans and seek feedback from anyone else that is interested.

TL;DR: We expect that no apps will break. You may have to update your Ruby or Rails version to keep current. If you expect this to be a significant burden, please let us know.

## Schema Dumper Update

Scenic 2.0 will add a topological alphabetical sort of views that are dumped to `schema.rb` (see #191). This should not cause any application issues. The first time you dump the schema after updating to Scenic 2.0 you may notice a large number of changes to `schema.rb`. In an abundance of caution, we have decided this warrants a major version bump. We suggest users run `rake db:schema:dump` after updating to Scenic 2.0 to capture the schema changes with that commit.

## Rails Version Support

We currently install on anything Rails 4.0 or later. We test against Rails 4.1 and newer. With the recent release of Rails 5.1, the Rails team considers Rails 4.2 and older unsupported.

By dropping support for Rails 4.2 and older we can get rid of a monkey patch and trim up our build matrix.

## Ruby Version Support

We currently require Ruby 2.1 or newer and test against 2.1, 2.2, 2.3, and 2.4. Scenic 2.0 will move to Ruby 2.2 or newer to be in line with current Rails requirements and allow us to trim up our build matrix.

**Comment by geoffharcourt** [comment]
I realize this might be a massive undertaking, but is there any possibility of being able to specify views that depend on other views in an order such that it's not necessary to use `structure.sql`? This has come up on more than one application I've worked on with Scenic.

**Comment by derekprior** [comment]
@geoffharcourt This should be handled. The schema dumper currently uses the order the views are defined in postgres when dumping the views. If postgres defines view "a" before view "b" then view "b" cannot depend on view "a". This should have been resolved in [version 1.1.0](https://github.com/thoughtbot/scenic/blob/master/NEWS.md#110---january-8-2016). Scenic 2.0 will change this slightly by sorting the views alphabetically within their topography.

Do you have an example where we're still not doing this properly?

**Comment by geoffharcourt** [comment]
My knowledge is out of date! Thanks for building that.

**Comment by calebthompson** [comment]
This plan looks good to me. I think we should get everything currently open (#200 and below) merged, resolved, or closed before releasing. There's at least one outstanding bug in issues, one is like to see a test case for before trying to resolve, a PR that'll be superseded, and one other hat I'm not sure of the implementation for but is a good feature to have. It's possible we could get that all done this week, but next is more likely (no estimates)

**Comment by calebthompson** [comment]
Is Ruby 2.2 maintained by the Ruby team?

**Comment by derekprior** [comment]
Ruby 2.2 is in security maintenance. It will be EOL'd in March of next year. See: https://www.ruby-lang.org/en/downloads/branches/

**Comment by devonestes** [comment]
So one thing that would be particularly sweet would be around the following scenario:

Materialized View 1 depends on Materialized View 2
Materialized View 2 depends on Materialized View 3
Materialized View 3 depends on Materialized View 4

If you want to change a column in materialized view 4, you first need to drop views 1, 2 and 3 (in that order), then make your change to materialized view 4, then re-build views 3, 2 and 1 (again, in the correct order). This is frequently a bummer - especially with a more tangled web of dependencies.

I would propose a feature that sort of functions like a cascading drop and then cascading recreation of those dependent materialized views. Scenic could handle the ordered dropping of dependent views or materialized views (as long as they're handled by Scenic so they can be re-built), and then handle the re-creation of those views or materialized views (again, in the correct order). For the rebuilding, we can default to using the most recent version (most recent defined by having the highest version number, i.e. `materialized_view_v03`).

If any of the dependencies anywhere along the way are _not_ managed by Scenic, the migration would rollback and the user would have to again manually handle the dropping an recreation of the dependent views. This provides convenience as well as safety from accidentally dropping things you don't want to drop by just doing a `CASCADE`.

All of that dependency information is already stored in Postgres, and we're already using it for our cascading materialized view refresh, so I think this could be implemented without a huge amount of changes to the codebase. It also wouldn't be a breaking change.

My only major concern with this feature is that it might make these sorts of deep dependency trees easier to do, which in the long run is a bad design decision. If it's too easy to do, then people might do more of it, which would be a bummer. But every now and then you end up with these things and you have to handle them, so it might be nice to have for those cases (i.e. the case I currently have...). I'd be curious to hear if others had any concerns around this, though!

**Comment by asselstine** [comment]
A topographical sort of the views would be excellent.  We're currently running into this issue when we replace views that use other views; since the view dump is sorted by the oid the order is incorrect.

++++1

**Comment by ebeigarts** [comment]
We were previously using `schema_plus_views`, but after migration to rails 5.1 we replaced it with `scenic`, we had created the dependent view recreation, [here is the gist](https://gist.github.com/ebeigarts/95f11f508a5ba42deae3cf857ead8a4e), see `recreate_dependent_views` method.

Also we had problems seeing what was actually changed in a view in PRs (one new file created), and `db/schema.rb` isn't the place to review changes in a PR, so we switched to using a single file and everyone edits`db/views/my_view.sql`, and when running `rake db:migrate` it copies the file with the latest version to `db/migrate/<timestamp>_my_view.sql`.

Our structure is:

- db/views/my_view.sql
- db/migrate/20170129101234_create_my_view.rb
- db/migrate/20170129101234_my_view.sql
- db/migrate/20170829133300_update_my_view.rb
- db/migrate/20170829133300_my_view.sql

The migrations look like this:

```
class UpdateMyView < MyEngine::Migration
  def change
    change_versioned_view :my_view
  end
end
```

Anyway, `scenic` works great, thanks

**Comment by seanfcarroll** [comment]
@devonestes this is definitely an issue, and even 'regular' views and depend on one another and therefore have a build order. The simple solution (employed in some large ERP systems) is to have a view priority. By default all views have a priority of 1, and can be created in any order. 

If a 2,3 etc is specified, then all the priority 1 views are created, then all the priority 2s etc. It could be defined in the model definition.

**Comment by iarie** [comment]
Hello everyone, I found difficult to refresh some matviews due to pg `statement_timeout`.
I ended up with few approaches to manage it.

Use wrapper: 
```ruby
  def refresh
    ActiveRecord::Base.connection.execute('SET statement_timeout = 10_000')
    Scenic.database.refresh_materialized_view(
       table_name, concurrently: concurrently, cascade: cascade
    )
  ensure
    ActiveRecord::Base.connection.execute("SET statement_timeout = #{ENV['DB_SESSION_TIMEOUT']}")
  end
```

Use different connection:
```yml
# config/database.yml
no_timeout_development:
  <<: *development
  variables:
    statement_timeout: 0
```
```ruby
class SomeMatView < ApplicationRecord
  establish_connection "no_timeout_#{Rails.env}".to_sym

  def self.refresh(concurrently: true, cascade: true)
    Scenic.database.refresh_materialized_view(
      table_name, concurrently: concurrently, cascade: cascade
    )
  end

  def readonly?
    true
  end
end
```
So I don't really know if this thing should be in Scenic or it more about DB connection configuration 
itself, but possible Scenic API may look like:
```ruby 
    Scenic.database.refresh_materialized_view(
      table_name, concurrently: concurrently, cascade: cascade, statement_timeout: 10_000
    )

    # Under the hood:
    # BEGIN;
    # SET LOCAL statement_timeout = 250;
    #   #{ sql_statement }
    # COMMIT;
```

**Comment by henrytseng** [comment]
Would love to follow up with this to see if there's still work being done on this release.  If not would love to get involved.  We have a initializer that adds our own topological sorting for our views in schema.rb already.

**Comment by derekprior** [comment]
There will a Scenic 2.0 some day. It will likely include some changes to schema dumping (hopefully consistent ordering), drop support for older rubies and older rails... This issue has outlived its usefulness so I'm going to close.
