### ISSUE TITLE
Can't `rake db:schema:load` on an already populated DB

### ISSUE THREAD

**Issue by pdfrod** [scenic-views/scenic#217]
I use `rake db:schema:load` as a convenient way to reload the DB schema of test applications. It used to work well on already populated databases, because Rails adds `force: :cascade` to the `create_table` statements. 

However, now that I'm using Scenic, the `rake db:schema:load` doesn't work anymore because the `create_view` statements fails if the view already exists. Using `rake db:drop` to clean the DB is not an option because I don't have permission to drop the entire database.

So what I propose is:
- make the `create_view` statements that are added to `schema.rb` have some sort of `force` option;
- `crate_view` statements with the `force` option would use `CREATE OR REPLACE` to create the view;
- perhaps create some configuration option to activate this behavior.

There were similar discussions in https://github.com/thoughtbot/scenic/issues/55 and https://github.com/thoughtbot/scenic/pull/58, but as far as I can tell it was never implemented a way to "force" a `create_view` in the `schema.rb`.

**Comment by derekprior** [comment]
`CREATE OR REPLACE` does not force a view to a particular definition. The replace will fail if the schema changes in an incompatible way. I believe the only way to do what you're after is to explicitly `DROP VIEW` followed by `CREATE VIEW`. We could potentially do that as an option to `create_view` and the schema generator could do that by default. I'm not horribly opposed to that.

For your particular use case, what's the difference between running `db:schema:load` and running `db:test:prepare`? The latter would work with the current schema, I think.

**Comment by xleninx** [comment]
I use the **`rake db:schema:load`** for the tests, because the project does not have all the migrations, therefore I can not use 'rake db: migrate' in the test environment.

But when I run **`rake db:schema:load`** in the test environment, it gives me the following: 

**`NoMethodError: undefined method create_view 'for <ActiveRecord :: Schema: 0x0055e11de12db0>`**

What can I do to make this work?

thank you in advance

**Comment by calebthompson** [comment]
If I recall correctly, db:schema:load doesn’t load gems. Try rake environment db:schema:load.

**Comment by xleninx** [comment]
unfortunately I have the same result.

![image](https://user-images.githubusercontent.com/2617679/50281281-bf3d0f00-042d-11e9-8224-3a4cf108ccb5.png)

On the other hand, i try **`rake db:test:prepare`** and I was able to recreate the test database with the dev database, but that command does not recreate the views of the database.

Thanks

**Comment by derekprior** [comment]
@pdfrod:

> Using rake db:drop to clean the DB is not an option because I don't have permission to drop the entire database.

This doesn't sound like a popular use case (not having rights to drop your development database?). Nonetheless, I think we'd at least discuss/entertain a PR that (optionally, perhaps) prefixes `create_view` statements with `drop_view` in the schema dumper.

@xleninx I'm afraid I've not run into this issue. Please be sure you have `scenic` available in the proper environments. If you have a minimal test app available, I'd be happy to look at your issue when I can.
