### ISSUE TITLE
Using Model Generator with Plural Name Causes File Write Error

### ISSUE THREAD

**Issue by stratigos** [scenic-views/scenic#245]
When I use a plural name for a model, I get the expected default warning that a pluralized name was used, and the filenames and model-class name will be converted to singular case. When the generator reaches the point where it edits the new model's file, it attempts to do so using a pluralized file name, and fails. 

E.g., running  `./bin/rails g scenic:model pluralized_things --materialized`  

will warn with:  
`[WARNING] The model name 'pluralized_things' was recognized as a plural, using the singular 'pluralized_thing' instead. Override with --force-plural or setup custom inflection rules for this noun before running the generator.`

and then: `create app/models/pluralized_thing.rb`  

and then will attempt to: `insert  app/models/pluralized_things.rb`

and raise the following exception:  
`/home/USER/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in 'binread': No such file or directory @ rb_sysopen - /home/USER/PATH-TO-APP/app/models/pluralized_things.rb (Errno::ENOENT)
	from /home/USER/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in 'replace!'`

I believe this step to edit the file needs to recognize that the singular name was forced, and drop the _s_ from the filename. 

Scenic Version: 1.2.0
Ruby: 2.3.3
Rails: 4.2

**Comment by derekprior** [comment]
This was fixed in 1.3 by this commit: https://github.com/scenic-views/scenic/pull/151/commits/35e3e5c412d9ef835d1cfd71bfbd060bf15ee3cb
