### ISSUE TITLE
1.4.2 release?

### ISSUE THREAD

**Issue by dougo** [scenic-views/scenic#251]
Hi, I just ran into this bug: https://github.com/thoughtbot/scenic/issues/230
It was fixed in January, but there hasn't been a new gem release since then.
Do you have a schedule for the next release?

**Comment by derekprior** [comment]
@dougo @edjames @aliou - You know what's better than 1.4.2? [1.5.0](https://github.com/scenic-views/scenic/blob/master/NEWS.md#150---february-8-2019). Sorry for the delay. We got new jobs, had other things going, etc. Hope you enjoy 1.5! 🚀

**Comment by aliou** [comment]
👏 👏 👏

**Comment by edjames** [comment]
@derekprior Sorry for the delayed response mate. Thanks very much for this.
