### ISSUE TITLE
Cascade dependencies not including materialized views when view name is part of dependency

### ISSUE THREAD

**Issue by dwillett** [scenic-views/scenic#258]
I'm seeing an issue where, because of the naming structure of my materialized views, the dependencies are not parsed correctly.

Example setup:
view 1: `namespaced.foo_90`
view 2: `namespaced.foo`

View 2 selects from view 1. The dependency on view 1 will not be refreshed when view 2 is refreshed with `cascade`

Looks like it's the fact that `#include?` is being used in 
```ruby
idx = sorted_arr.find_index do |dep|
  dep.include?(view_to_refresh.to_s)
end
```

**Comment by derekprior** [comment]
Fixed in #270
