### ISSUE TITLE
Rails upgrade from 5.0.X to 5.2.X | Views with custom DB schema no longer work in schema.rb

### ISSUE THREAD

**Issue by douglasrlee** [scenic-views/scenic#262]
We recently upgraded our application from rails 5.0.X to 5.2.X and it seems like in rails 5.1.X they changed how the schema.rb is laid out.. I think.

Previous schema definitions for views were in the `schema.rb` like so:
```
create_view :accounts_view, sql_definition:<<-SQL
  select things from table;
SQL
```
but in the newer rails version it is:
```
create_view "analytics.accounts_view",  sql_definition: <<-SQL
  select things from table;
SQL
```

The problem being in the new version it is creating the view with the `analytics` schema that does not exist whereas previously it created just the view in the public schema.

Is this working as expected??

Should we have to setup the db with the `analytics` schema before we load the schema?

**Comment by douglasrlee** [comment]
That is correct. I actually think I found out after this that there was a bug that was fixed in the Rails upgrade that made this work properly. The issue being that it still requires the `analytics` schema to be created first.

Our workaround for right now is to change the application to use structure.sql vs schema.rb.

**Comment by calebthompson** [comment]
Interesting. So the new bug is that you have to have the analytics schema to create the table, but neither Scenic nor Rails is creating it for you. I don't see anything in the Rails docs that suggests alternative schemas for table creation or migrations, though I do see ActiveRecord::Base methods for specifying schemas and database config options for setting up search paths.

@derekprior thoughts? We could add schema creation easily enough as a separate migration/schema method, but doing so seems out of scope. OTOH, we currently support creating views in a schema if it's specified as above, and the schema already exists.

**Comment by derekprior** [comment]
I think schema creation is out of scope for Scenic. We support views being created in schemas, but that was on the assumption the schema existed.

One thing I recall doing in the past was [enhancing rake tasks](https://til-engineering.nulogy.com/posts/43e3aff936-enhancing-rake-tasks) (`db:create`, I think?) to ensure the schema exists. There may be a separate schema plugin that gives you good migration support insted, but you'd have to edit old migrations to ensure the schema is created before the first time you create a view in it.

**Comment by derekprior** [comment]
I don't think there's anything to be done here on the scenic side.
