### ISSUE TITLE
alias_method not possible?

### ISSUE THREAD

**Issue by richmolj** [scenic-views/scenic#266]
When using vanilla ActiveRecord, `alias_method` works fine:

```ruby
class Post < ApplicationRecord
  alias_method :title2, :title
end
```

But when AR is backed by a view, this will blow up:

```
NameError: undefined method `title' for class `#<Class:0x00007ffe4c502718>'
```

I'm not sure if this is a scenic problem, or an ActiveRecord bug, but haven't been able to find any information about this in either repo's issues.

**Comment by calebthompson** [comment]
What version of Rails are you using?

**Comment by richmolj** [comment]
`5.2.1`

**Comment by richmolj** [comment]
This is me being a little silly. I should have used `alias_attribute` not `alias_method`. Thanks!
