### ISSUE TITLE
Semicolon in SQL file causes materialize: {no_data: true} to blow up

### ISSUE THREAD

**Issue by kitsunde** [scenic-views/scenic#272]
If I terminate my view statement with a `;` and try to create a view with `materialize{no_data: true}` it raises:

```bash
Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "DATA"
LINE 16:   WITH NO DATA;
```

It would be nice if it could either handle that, or present a more complete error message.

**Comment by derekprior** [comment]
@kitsunde, I have pushed #273 to fix this. Wanna give that a review? I can push a patch release once merged.

**Comment by derekprior** [comment]
v1.5.1 is released with this fix.
