### ISSUE TITLE
Refresh cascade:true, concurrently: true refreshes the underlying mat views without concurrency

### ISSUE THREAD

**Issue by yonibaciu** [scenic-views/scenic#276]
Hi,

concurrently:true is not passed down to refresh_dependencies_for which results in depending mat views being refreshed without concurrency.

```
def refresh_materialized_view(name, concurrently: false, cascade: false)
  raise_unless_materialized_views_supported
  if cascade
    refresh_dependencies_for(name)
  end
  .
  .
end
```

**Comment by derekprior** [comment]
@yonibaciu - I've opened #288 to fix. Want to give that shot locally to see if it behaves as you would expect?
