### ISSUE TITLE
How to configure a primary key based on multiple columns ?

### ISSUE THREAD

**Issue by webattitude** [scenic-views/scenic#277]
I'm creating a view which is union of two tables. But ids can conflict.
I suppose I have to set id and type as primary_key, but it does not seem to be supported...
Any suggestion ?

**Comment by derekprior** [comment]
I'm not an expert on this matter, but what if in your view you created a single column which was a concatenation on the type and id?

**Comment by webattitude** [comment]
Yep thx, I will do that then, although I was not very confident on the performance side of this solution.
