### ISSUE TITLE
Is it possible to call current_user in view

### ISSUE THREAD

**Issue by sonq** [scenic-views/scenic#278]
Hello,

What i would like to do is generate a dashboard and values will simply come from the view that i will create. Dashboard will be specific to users so i would like to achieve something like

select *
from users
where id = current_user

By the way i am using devise. 

Thanks and regards!

**Comment by calebthompson** [comment]
No, what you’d do is create a view with all users and with whatever fields, joins, calculations for all users. Then when you want to query it you pull records for a specific user.
