### ISSUE TITLE
How to load data into a model?

### ISSUE THREAD

**Issue by 9mm** [scenic-views/scenic#281]
I've read the docs a few times, but I'm wondering if I can do something like this:

View code:

   -- lots of complicated SQL which results in an `invoices` table

Can I load this into `Invoice` when I call `SpecialSubsetOfInvoices` view model? 

The fields will be identical, but instead of getting a SpecialSubsetOfInvoices back, I want to get an Invoice back, or, at the very least, I want to be able to call all the methods I normally can call on Invoice.

I saw something about polymorphic true and all this, but I dont want to add associations, I just want to say "this is identical to an invoice" (including primary key

Otherwise, I need to do an unecessary query just to match it with an actual invoice of the same id

**Comment by derekprior** [comment]
I’m afraid I don’t really get what you are after. If you want to get one class of thing from the database but have it act as a different class, look into `becomes`: https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-becomes

**Comment by 9mm** [comment]
That's exactly what I needed:

```
  def latest_lease
    LatestLeaseForUnit
      .find_by(unit_id: id)
      .try(:becomes, Lease)
  end
```
