### ISSUE TITLE
Usage outside of Rails?

### ISSUE THREAD

**Issue by sudostack** [scenic-views/scenic#283]
I'm currently working on a project using Grape API with Active Record, but no Rails.

I didn't dig too deeply into the source code for the project, but I'm curious as to whether use of this gem is strictly coupled to Rails. My understanding is that the coupling is more with Active Record than Rails. 

So aside from the generator(s), is it okay to use outside of Rails? Is there something I'm overlooking?

**Comment by derekprior** [comment]
There is a dependency on activerecord and railties (for Engine-specific code). I don’t know what taking a railties dependency for non-rails apps would do.

**Comment by sudostack** [comment]
@derekprior thanks for sharing that tidbit. I'll experiment, but appreciate the prompt response!
