### ISSUE TITLE
create_view not reversible with version option

### ISSUE THREAD

**Issue by mdavidn** [scenic-views/scenic#286]
The `create_view` statement is not reversible with the `:version` option.

I often find myself needing to drop and recreate hierarchies of views when they reference each other. That leads to migrations like this:

```rb
class UpdateInnerViewToVersion2 < ActiveRecord::Migration[5.2]
  def change
    drop_view :outer_view, revert_to_version: 2
    update_view :inner_view, materialized: true, version: 2, revert_to_version: 1
    create_view :outer_view, version: 2   # <-- Not reversible!
  end
end
```

```
== 20191207005356 UpdateInnerViewToVersion2: reverting ===========
-- drop_view(:outer_view, {:version=>2})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown keyword: version
[redacted]/gems/scenic-1.5.1/lib/scenic/statements.rb:63:in `drop_view'
```

I did expect this migration to be reversible.

**Comment by mdavidn** [comment]
And, while we're on the subject, I feel `:revert_to_version` should default to `version - 1`. 🤞

**Comment by derekprior** [comment]
We don’t know which version you want to revert to. We can assume n-1 but that’s not necessarily correct. 

`create_view` takes a `revert_to_version` argument for this reason.

**Comment by mdavidn** [comment]
That doesn't make sense. The inverse of `create_view` is `drop_view`, which does not need a version specified. It drops the view.

Note that `create_view` is reversible when _no_ `:version` option is given.

I think this is clearly a bug.

**Comment by derekprior** [comment]
Ah, I think i misread this the first time around. This should be fixable in the command recorder if anyone wants to give this a shot.

**Comment by derekprior** [comment]
See #289 for potential fix

**Comment by dreig** [comment]
This same error happens if `create_view` uses the `:sql_definition` option. In general it looks like `Scenic::Adapters::Postgres#drop_view` only takes one parameter (the name of the view to drop), so any option will make `create_view` irreversible.
