### ISSUE TITLE
Unable to implement database-specific options in adapters

### ISSUE THREAD

**Issue by brianthoman** [scenic-views/scenic#301]
Hello,
I need to create a materialized view that looks something like this:
```sql
CREATE MATERIALIZED VIEW my_mview
USING TRUSTED CONSTRAINTS
AS
SELECT ...
```
The second line is the tricky one. It's one of [many options](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_6002.htm#i2145767) available when creating an Oracle materialized view. I don't think there's currently any way to include these options using Scenic.

I know this will ultimately need to be supported by the Oracle adapter, but I think we're missing a way to pass options through Scenic and on to the adapters so that they can do so. I only see support for a `NO DATA` option for PostgreSQL.

If this seems like a useful feature to add to Scenic, I'd  be happy to work on a PR, but I'd appreciate some input on how it should be implemented. Should it be a new method? Should we add an `options` param to the existing methods and let the adapters document what they expect it to contain? Would the `no_data` option stay where it is? I'm very open to ideas.

Thanks!

**Comment by derekprior** [comment]
For something like this, I would suggest adding an option similar to the `no_data` option on the postgres side. You'd have to override the schema statement as well as implement support in the adapter. I can't really think of a great way around this.
