### ISSUE TITLE
New version 1.5.3 released without reference in the repo?

### ISSUE THREAD

**Issue by bf4** [scenic-views/scenic#305]
[rubygems has a new version 1.5.3](https://rubygems.org/gems/scenic/versions/1.5.3) released by @calebthompson but there's no reference in the repo. Odd, right?

**Comment by calebthompson** [comment]
That was me, I guess I forgot to push the tag. I’ll do that shortly.
GitHub <notifications@github.com> wrote:
“rubygems has a new version 1.5.3 released by @calebthompson but there's no reference in the repo. Odd, right?”

**Comment by bf4** [comment]
ah, ok. I just did a gem diff locally to see if you'd been hacked :)

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index d1d194f..bd318b2 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -5,7 +5,7 @@ changelog, see the [commits] for each version via the version links.
 
 [commits]: https://github.com/scenic-views/scenic/commits/master
 
-## [1.5.2] - February 6, 2019
+## [1.5.2] - February 6, 2020
 
 ### Fixed
 
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 72d2f3f..9b81762 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -10,10 +10,12 @@ agree to abide by our [code of conduct].
 1. Fork the repository.
 2. Run `bin/setup`, which will install dependencies and create the dummy
    application database.
-3. Run `bin/appraisal rake` to verify that the tests pass against all
-   supported versions of Rails.
+3. Run `rake` to verify that the tests pass against the version of Rails you are
+   running locally.
 4. Make your change with new passing tests, following existing style.
 5. Write a [good commit message], push your fork, and submit a pull request.
+6. CI will run the test suite on all configured versions of Ruby and Rails.
+   Address any failures.
 
 [good commit message]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
 
diff --git a/Gemfile b/Gemfile
index 9bb0840..5740886 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,3 +2,15 @@ source "https://rubygems.org"
 
 # Specify your gem's dependencies in scenic.gemspec
 gemspec
+
+rails_version = ENV.fetch("RAILS_VERSION", "6.0")
+
+if rails_version == "master"
+  rails_constraint = { github: "rails/rails" }
+else
+  rails_constraint = "~> #{rails_version}.0"
+end
+
+gem "rails", rails_constraint
+gem "sprockets", "< 4.0.0"
+gem "pg", "~> 1.1"
diff --git a/LICENSE.txt b/LICENSE.txt
index 92d9daf..b2aec8b 100644
--- a/LICENSE.txt
+++ b/LICENSE.txt
@@ -1,4 +1,4 @@
-Copyright (c) 2014-2016 Derek Prior, Caleb Thompson, and thoughtbot.
+Copyright (c) 2014-2020 Derek Prior, Caleb Hearth, and thoughtbot.
 
 MIT License
 
diff --git a/README.md b/README.md
index 7195549..3999277 100644
--- a/README.md
+++ b/README.md
@@ -2,7 +2,7 @@
 
 ![Scenic Landscape](https://user-images.githubusercontent.com/152152/49344534-a8817480-f646-11e8-8431-3d95d349c070.png)
 
-[![Build Status](https://travis-ci.org/scenic-views/scenic.svg?branch=master)](https://travis-ci.org/scenic-views/scenic)
+[![Build Status](https://github.com/scenic-views/scenic/workflows/CI/badge.svg)](https://github.com/scenic-views/scenic/actions?query=workflow%3ACI+branch%3Amaster)
 [![Documentation Quality](http://inch-ci.org/github/scenic-views/scenic.svg?branch=master)](http://inch-ci.org/github/scenic-views/scenic)
 [![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)
 
@@ -94,7 +94,7 @@ when some of those views may be materialized and take a long time to recreate.
 
 You can use `replace_view` to generate a CREATE OR REPLACE VIEW SQL statement.
 
-See postgresql documentation on how this works:
+See Postgres documentation on how this works:
 http://www.postgresql.org/docs/current/static/sql-createview.html
 
 To start replacing a view run the generator like for a regular change:
@@ -135,7 +135,7 @@ ActiveRecord or ARel queries. As far as ActiveRecord is concerned, a view is
 no different than a table.
 
 ```ruby
-class SearchResult < ActiveRecord::Base
+class SearchResult < ApplicationRecord
   belongs_to :searchable, polymorphic: true
 
   # this isn't strictly necessary, but it will prevent
@@ -218,7 +218,7 @@ You can get around these issues by setting the primary key column on your Rails
 model like so:
 
 ```ruby
-class People < ActiveRecord::Base
+class People < ApplicationRecord
   self.primary_key = :my_unique_identifier_field
 end
 ```
@@ -255,12 +255,15 @@ meet your needs:
 * [scenic_sqlite_adapter](https://github.com/pdebelak/scenic_sqlite_adapter)
 * [scenic-mysql_adapter](https://github.com/EmpaticoOrg/scenic-mysql_adapter)
 * [scenic-sqlserver-adapter](https://github.com/ClickMechanic/scenic_sqlserver_adapter)
-* [scenic-oracle_enhanced_adapter](https://github.com/PMACS/scenic_oracle_enhanced_adapter)
+* [scenic-oracle_adapter](https://github.com/cdinger/scenic-oracle_adapter)
+
+Please note that the maintainers of Scenic make no assertions about the
+quality or security of the above adapters.
 
 ## About
 
-Scenic is maintained by [Derek Prior], [Caleb Thompson], and you, our
+Scenic is maintained by [Derek Prior], [Caleb Hearth], and you, our
 contributors.
 
 [Derek Prior]: http://prioritized.net
-[Caleb Thompson]: http://calebthompson.io
+[Caleb Hearth]: http://calebhearth.com
diff --git a/bin/setup b/bin/setup
index c8af19f..3c9a11d 100755
--- a/bin/setup
+++ b/bin/setup
@@ -2,12 +2,17 @@
 
 set -e
 
+# CI-specific setup
+if [ -n "$GITHUB_ACTIONS" ]; then
+  bundle config path vendor/bundle
+  bundle config jobs 4
+  bundle config retry 3
+  git config --global user.name 'GitHub Actions'
+  git config --global user.email 'github-actions@example.com'
+fi
+
 gem install bundler --conservative
 bundle check || bundle install
 
-if [ -z "$CI" ]; then
-  bundle exec appraisal install
-fi
-
 bundle exec rake dummy:db:drop
 bundle exec rake dummy:db:create
diff --git a/checksums.yaml b/checksums.yaml
index 2a52bb1..1589965 100644
--- a/checksums.yaml
+++ b/checksums.yaml
@@ -1,7 +1,7 @@
 ---
 SHA256:
-  metadata.gz: 75afe5531011de8c35f2272af574763575bdb4d9f9650eeb2845a3f163b1e941
-  data.tar.gz: a7ded9f2177997aba8c3c424e04c2aed14f08a2f452d4ab74d2030d692fe1e7c
+  metadata.gz: a5199c8d00d9c719110d712116605b4e7b55fe8094748e8532b6a61c7c36a88a
+  data.tar.gz: e9e5c90ed46501f15c09f3215e56a38ec7cd9e32b81008e651ec8d23d1a23916
 SHA512:
-  metadata.gz: f1d00648e7f6c73b76242d43b3d49456afbc531a3a562dd43525b1f45f0b440f8650f1d4fb9459780aba7e46e87b49d33b3f7b92693ae43f03d51ea1fee39a67
-  data.tar.gz: 7da8bfdf0cac0c7bea6a7e67f09a37767943d5e6f2608ffb478db0b2884a93bc76e06b2b0d8fcf52a7d95d7b10d154d3b7cd2065de022a44d669f61b88699cfa
+  metadata.gz: b75a5a869a500feddb5b45ec1f2b93eb9eb605c76d1326462eda78fddd888c2010f8692de141c275133553d200caef74c087c60a8b0c6e2e87b2cbdc751ef43d
+  data.tar.gz: 4580819daacf5bd817e1ef4a2fb127c825615286173bedb2a0ba61be19aaac5e7a963d5a6cdd9a435c09db13337a188c8c2fb4c4fa718276d3980d938ad4aa4b
diff --git a/data.tar b/data.tar
index dccc036..8f0f68a 100644
Binary files a/data.tar and b/data.tar differ
diff --git a/lib/scenic/version.rb b/lib/scenic/version.rb
index 3161904..0d1b0cf 100644
--- a/lib/scenic/version.rb
+++ b/lib/scenic/version.rb
@@ -1,3 +1,3 @@
 module Scenic
-  VERSION = "1.5.2".freeze
+  VERSION = "1.5.3".freeze
 end
diff --git a/metadata b/metadata
index a843e78..322fe9a 100644
--- a/metadata
+++ b/metadata
@@ -1,30 +1,16 @@
 --- !ruby/object:Gem::Specification
 name: scenic
 version: !ruby/object:Gem::Version
-  version: 1.5.2
+  version: 1.5.3
 platform: ruby
 authors:
 - Derek Prior
-- Caleb Thompson
-autorequire: 
+- Caleb Hearth
+autorequire:
 bindir: bin
 cert_chain: []
-date: 2020-02-06 00:00:00.000000000 Z
+date: 2020-09-15 00:00:00.000000000 Z
 dependencies:
-- !ruby/object:Gem::Dependency
-  name: appraisal
-  requirement: !ruby/object:Gem::Requirement
-    requirements:
-    - - ">="
-      - !ruby/object:Gem::Version
-        version: '0'
-  type: :development
-  prerelease: false
-  version_requirements: !ruby/object:Gem::Requirement
-    requirements:
-    - - ">="
-      - !ruby/object:Gem::Version
-        version: '0'
 - !ruby/object:Gem::Dependency
   name: bundler
   requirement: !ruby/object:Gem::Requirement
@@ -184,17 +170,16 @@ description: |2
       in Rails
 email:
 - derekprior@gmail.com
-- caleb@calebthompson.io
+- caleb@calebhearth.com
 executables: []
 extensions: []
 extra_rdoc_files: []
 files:
+- ".github/workflows/ci.yml"
 - ".gitignore"
 - ".hound.yml"
 - ".rubocop.yml"
-- ".travis.yml"
 - ".yardopts"
-- Appraisals
 - CHANGELOG.md
 - CODE_OF_CONDUCT.md
 - CONTRIBUTING.md
@@ -202,14 +187,11 @@ files:
 - LICENSE.txt
 - README.md
 - Rakefile
-- bin/appraisal
+- SECURITY.md
 - bin/rake
 - bin/rspec
 - bin/setup
 - bin/yard
-- gemfiles/rails52.gemfile
-- gemfiles/rails60.gemfile
-- gemfiles/rails_edge.gemfile
 - lib/generators/scenic/generators.rb
 - lib/generators/scenic/materializable.rb
 - lib/generators/scenic/model/USAGE
@@ -273,7 +255,7 @@ homepage: https://github.com/scenic-views/scenic
 licenses:
 - MIT
 metadata: {}
-post_install_message: 
+post_install_message:
 rdoc_options: []
 require_paths:
 - lib
@@ -288,8 +270,8 @@ required_rubygems_version: !ruby/object:Gem::Requirement
     - !ruby/object:Gem::Version
       version: '0'
 requirements: []
-rubygems_version: 3.0.1
-signing_key: 
+rubygems_version: 3.1.2
+signing_key:
 specification_version: 4
 summary: Support for database views in Rails migrations
 test_files:
diff --git a/scenic.gemspec b/scenic.gemspec
index 40f0d1e..5f6f069 100644
--- a/scenic.gemspec
+++ b/scenic.gemspec
@@ -5,8 +5,8 @@ require "scenic/version"
 Gem::Specification.new do |spec|
   spec.name          = "scenic"
   spec.version       = Scenic::VERSION
-  spec.authors       = ["Derek Prior", "Caleb Thompson"]
-  spec.email         = ["derekprior@gmail.com", "caleb@calebthompson.io"]
+  spec.authors       = ["Derek Prior", "Caleb Hearth"]
+  spec.email         = ["derekprior@gmail.com", "caleb@calebhearth.com"]
   spec.summary       = "Support for database views in Rails migrations"
   spec.description   = <<-DESCRIPTION
     Adds methods to ActiveRecord::Migration to create and manage database views
@@ -19,7 +19,6 @@ Gem::Specification.new do |spec|
   spec.test_files    = spec.files.grep(%r{^spec/})
   spec.require_paths = ["lib"]
 
-  spec.add_development_dependency "appraisal"
   spec.add_development_dependency "bundler", ">= 1.5"
   spec.add_development_dependency "database_cleaner"
   spec.add_development_dependency "rake"
diff --git a/spec/dummy/config/database.yml b/spec/dummy/config/database.yml
index a82e9da..2207510 100644
--- a/spec/dummy/config/database.yml
+++ b/spec/dummy/config/database.yml
@@ -2,7 +2,12 @@ development: &default
   adapter: postgresql
   database: dummy_development
   encoding: unicode
+  host: localhost
   pool: 5
+  <% if ENV.fetch("GITHUB_ACTIONS", false) %>
+  username: <%= ENV.fetch("POSTGRES_USER") %>
+  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
+  <% end %>
 
 test:
   <<: *default
```

**Comment by bf4** [comment]
missing the changelog entry too (dependabot brought it up ;)

**Comment by calebthompson** [comment]
Thanks. I've pushed the changes for v1.5.3 and a new version v1.5.4 to fix the missing changelog.
GitHub <notifications@github.com> wrote:
“missing the changelog entry too (dependabot brought it up ;)”

**Comment by bf4** [comment]
Thanks for your work.  We're actually using this just for the generators and the `::Scenic::Definition.new(scenic_view_name, scenic_view_version).to_sql` right now since we already had something going which didn't track versions.  Started using fx first which I imagine was inspired by this. The versioned view migrations are super nice.  And we can specify our indices and whatever in our own 'view migration' thingee
