### ISSUE TITLE
Support for postgresql GENERATED columns?

### ISSUE THREAD

**Issue by marksiemers** [scenic-views/scenic#307]
> A generated column is a special column that is always computed from other columns. Thus, it is for columns what a view is for tables.

Source: https://www.postgresql.org/docs/12/ddl-generated-columns.html

Wondering if there are any plans for scenic to support generated columns, as postgres sees them as view for columns.

We have a need for a set of generated columns and we'll be switching to `structure.sql` to support them, but we don't want to lose the great versioning that scenic provides for creating and updating views.

**Comment by marksiemers** [comment]
After a little more research I see there is a PR to provide this in activerecord directly: https://github.com/rails/rails/pull/39368

**Comment by marksiemers** [comment]
Assuming this will be taken care of in activerecord.

**Comment by calebthompson** [comment]
Thanks for the update! If that PR doesn't land, we'd at least consider it in Scenic.
