### ISSUE TITLE
rake db:migrate 

### ISSUE THREAD

**Issue by interpegasus** [scenic-views/scenic#308]
Hi, Currently I have a rails 6 app with the mysql adapter on AWS Aurora, and `rake db:migrate` returns:

**Input**

`RAILS_ENV=development bundle exec rake db:migrate `

**Output**
```
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'current_schemas(false))
            ORDER BY c.oid' at line 11
```

$ mysql --version 
mysql  Ver 8.0.21 for osx10.15 on x86_64 (Homebrew)

`rake db:migrate`  only works when removing / commenting "scenic" in Gemfile. I would like to know if there is a MySQL version that should be used locally, or scenic branch to fix this? Thanks

**Comment by interpegasus** [comment]
Perhaps a related issue:
https://github.com/scenic-views/scenic/issues/291

**Comment by derekprior** [comment]
The scenic project itself does not support MySQL. There are third party adapters that may work for you. See the FAQ: https://github.com/scenic-views/scenic#faqs
