### ISSUE TITLE
Specify environment or db name when creating a view. 

### ISSUE THREAD

**Issue by konung** [scenic-views/scenic#309]
Hi. 

Great gem. Thank you!

We ran into an issue where I tried to pull tables from different DBs to create a view (LEGACY DB & Production DB) . But unfortunately I have to hardcode  DB name to make it work, which means it doesn't work well in development or testing. 
Am I missing soemthing?

Here is an example (see DEVELOPMENT in caps) . I ommitted 20 other fields I'm pulling for clarity.

```sql
SELECT
	lo.unitno AS order_id,
	lo.invcustnam AS customer_name,
	sh.id AS shipment_id,
	sh.tracking_number AS shipment_tracking_number,
FROM
	legacy_DEVELOPMENT.orders AS lo
	LEFT JOIN api_DEVELOPMENT.shipments AS sh ON sh.shipmentable_type = "ExchangeOrder" 
	AND sh.shipmentable_id = lo.unitno 
WHERE
     lo.unitno IS NOT NULL 
ORDER BY
	order_id
```

If instead we could interpolate `Rails.env`, that would solve this problem for different environments. 

```sql
SELECT
	lo.unitno AS order_id,
	lo.invcustnam AS customer_name,
	sh.id AS shipment_id,
	sh.tracking_number AS shipment_tracking_number,
FROM
	legacy_#{Rails.env}.orders AS lo
	LEFT JOIN api_#{Rails.env}.shipments AS sh ON sh.shipmentable_type = "ExchangeOrder" 
	AND sh.shipmentable_id = lo.unitno 
WHERE
     lo.unitno IS NOT NULL 
ORDER BY
	order_id
```

P.S.:

This might be MySQL / MariaDB specific. I know a while back it was not possible in PostgreSQL, but things might have changed.

**Comment by claasz** [comment]
Hi, we had the same problem here. As a woraround, we added a monkey patch:

```
# /config/initializers/scenic_monkey_patch.rb

module Scenic
  class Definition

    def to_sql
      c = File.read(full_path).tap do |content|
        if content.empty?
          raise "Define view query in #{path} before migrating."
        end
      end
      eval("\"" + c + "\"")
    end
  end
end
```

**Comment by derekprior** [comment]
This seems like a use case for multiple database support in Rails? https://guides.rubyonrails.org/active_record_multiple_databases.html

**Comment by claasz** [comment]
It's not clear to me how Rails multiple database support would solve the problem described above? In our case, we want to create a view which definition includes a environment dependent database name. As long as there's no interpolation happening  for the view definition, I cannot see how this could be done.

**Comment by derekprior** [comment]
You're probably right. I didn't read carefully enough. Still, this is not something we are likely to support.

The goal of this gem is to offer repeatable, consistent view management and interpolation would be a detriment to that.

**Comment by konung** [comment]
Hmm. Ran into this issue again 4 years later, and came back to my own ticket (as it turns out) 🤦 

Just an FYI, the solution I ended up using to keep consistent with the goal of the gem, is to keep 3 copies of the view, with env extension - this way SQL is clean. 

```bash
product_with_line_development_v01.sql
product_with_line_test_v01.sql
product_with_line_production_v01.sql
 ```
 
 ```ruby
 class CreateProductWithLineView < ActiveRecord::Migration
  def up
    view_name = "product_with_line_#{Rails.env}_v01"
    sql_definition = File.read(Rails.root.join("db/views/#{view_name}.sql"))

    create_view :product_with_line, sql_definition: sql_definition
  end

  def down
    drop_view :product_with_line
  end
end
```

Yes there is duplication of SQL code, but per @derekprior "The goal of this gem is to offer repeatable, consistent view management and interpolation would be a detriment to that." - so I think it's justfied.
