### ISSUE TITLE
db:schema:load load fails due to a syntax error 

### ISSUE THREAD

**Issue by wasabigeek** [scenic-views/scenic#315]
Setup
- macOS 10.15.7
- ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]
- rails 5.2.4.4
- scenic 1.5.2

We're getting this error when trying to run `db:schema:load`:
```
Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "{"
LINE 1: CREATE VIEW example AS {:sql_definition=>"     ...
```
Our schema.rb (from a previous `db:schema:dump`)
```ruby
  create_view "example", sql_definition: <<-SQL
      SELECT ...;
  SQL
```

**Comment by wasabigeek** [comment]
Ok I found out why, looks like a clash with https://github.com/nullobject/rein#views. If anyone has ready advice on how we could overcome this, would love to hear it! Will close this for now.

**Comment by derekprior** [comment]
I'm not familiar with that gem in particular, but we've seen these types of conflicts before. Unfortunately, gems that operate in this space do so without an official API so we are in monkey patch land. 

Sometimes you can change the order things are required (generally by reordering the gems in the gemfile) can do the trick.

**Comment by wasabigeek** [comment]
Thanks @derekprior!

Turns out `rein` was a forgotten gem in our codebase and effectively does `ActiveRecord::Migration.include(...)`, so I would think re-ordering the gems wouldn't help since it seems `scenic` patches `ActiveRecord::ConnectionAdapters::AbstractAdapter` instead (not familiar with how the migration is instantiated in Rails though, so maybe I'm wrong? Looking forward to being corrected if so 😄 ). We might likewise monkey patch in an initializer (`ActiveRecord::Migration.prepend Scenic::Statements`) while deciding on the approach. 

(I've also learnt that `rein` doesn't dump to schema.rb, so we might shift back to structure.sql, which obviates this problem.)
