### ISSUE TITLE
Any support for MERGE VIEW?

### ISSUE THREAD

**Issue by Victorcorcos** [scenic-views/scenic#324]
Hello all!

Sometimes, the execution of SQL Views can be very, very slow, due to some problems like full table scan.

A solution to this problem is the `MERGE VIEW` SQL statement, like this one right here: https://stackoverflow.com/a/7536977/7644846

Does this gem have any support to the `MERGE VIEW` statement like this one?

Thanks!

**Comment by fatkodima** [comment]
This gem is for postgres only, but mentioned feature is mysql only.

**Comment by derekprior** [comment]
See the MySQL implementation linked in the README
