### ISSUE TITLE
Declaring column names in PostgreSQL

### ISSUE THREAD

**Issue by JoshCheek** [scenic-views/scenic#329]
Hi. On the PostgreSQL [docs](https://www.postgresql.org/docs/9.2/sql-createview.html),
they show that you can pass the column names to the view:

```
CREATE [ OR REPLACE ] [ TEMP | TEMPORARY ] VIEW name [ ( column_name [, ...] ) ]
    [ WITH ( view_option_name [= view_option_value] [, ... ] ) ]
    AS query
```

This might be useful when unioning tables with disjoint columns, eg here we can positionally select `null`

```ruby
require 'pg'
PG.connect.exec(<<~SQL).to_a
create temp table omgs(a text, b text);
create temp table wtfs(b text, c text);

insert into omgs (a, b) values ('a1', 'b1'      ),
                               ('a2', 'b2'      );
insert into wtfs (b, c) values (      'b3', 'c1'),
                               (      'b4', 'c2');

create temp view bbqs (a, b, c) as
  select a, b, null from omgs
  union
  select null, b, c from wtfs;

select * from bbqs order by b;
SQL
# => [{"a"=>"a1", "b"=>"b1", "c"=>nil},
#     {"a"=>"a2", "b"=>"b2", "c"=>nil},
#     {"a"=>nil, "b"=>"b3", "c"=>"c1"},
#     {"a"=>nil, "b"=>"b4", "c"=>"c2"}]
```

Anyway, might be nice for Scenic to support this. I haven't tried it yet to confirm that it is relevantly better than having each `select` statement specify what column the `null` value is for, so I can't say with confidence that this is an important feature, but figured I'd bring it up since I didn't see any other conversations about it.

**Comment by calebthompson** [comment]
I believe this can be accomplished with this SQL:

```sql
create temp view bbqs (a, b, c) as
  select a, b, null AS c from omgs
  union
  select null AS a, b, c from wtfs;
```

Which isn't to say that this isn't a good idea, just that it's possible without any change.

**Comment by JoshCheek** [comment]
Guessing that was supposed to be:

```sql
create temp view bbqs as
  select a, b, null as c from omgs
  union
  select null, b, c from wtfs;
```

**Comment by derekprior** [comment]
I'm inclined to say that you should use `as` in your component SQL queries when using scenic rather than offering another option on `create_view`, `update_view`, `replace_view`, `drop_view`, etc. 

If there are strong feelings that this is a necessary feature, we can reconsider.
