### ISSUE TITLE
Automatically transfer permissions when replacing a view

### ISSUE THREAD

**Issue by danieldiekmeier** [scenic-views/scenic#338]
Hey there,

in our app, we're using Scenic as a kind of "Access Control": We create views that contain a subset of the columns of our actual tables, and we have a dedicated Postgres user that can only `SELECT` from the Scenic views.

Our problem is: When we use `update_view`, the old view gets destroyed, but the new view doesn't automatically receive the permissions of the old one. We have to manually go in and grant the permissions again.

We understand that this is how Postgres works, but we were wondering if you'd be interested in supporting this use case, where Scenic would "transfer" the permissions when updating a view.

We'd be happy to provide an implementation and create a Pull Request, if this is something you can see Scenic supporting.

Thanks for your consideration!

**Comment by derekprior** [comment]
We already have a pattern for something similar with indexes on materialized views but I'm not sure we should extend it for this use case which seems unlikely to be common.

I'd encourage you to look at how Index Reapplication works to see how you might do permission re-application -- perhaps as an extension to scenic you could use.

I'm not terribly incliuned to support this inside Scenic at the moment, but I could be swayed by some combination of:

1. A number of people that need this functionality
2. An implementation that is easily understood
3. An argument convincing me this isn't a slippery slop towards supporting just about anything someone can associate with a view (if we support indexes and permissions, is there going to be something _else_ after that?)

I'm going to close this for now given that I'm not convinced we should add and maintain this, but could revisit
