### ISSUE TITLE
"pg_stat_statements_info" already exists when running rails db:test:load 

### ISSUE THREAD

**Issue by stephichau** [scenic-views/scenic#348]
I ran a scenic migration to create a materialized view and it adds another `create_view` in my `schema.db`

```ruby
create_view "pg_stat_statements_info", sql_definition: <<-SQL
      SELECT pg_stat_statements_info.dealloc,
      pg_stat_statements_info.stats_reset
     FROM pg_stat_statements_info() pg_stat_statements_info(dealloc, stats_reset);
  SQL
```

When running `db:test:load`, I get the following error:

```bash
Caused by:
PG::DuplicateTable: ERROR:  relation "pg_stat_statements_info" already exists
```

Is there any config I might be missing? 🤔

**Comment by calebhearth** [comment]
Hmm looks like you may have found a bug with our compatibility with Postgres 14, [which added this view](https://www.postgresql.org/docs/14/release-14.html#:~:text=Add%20pg_stat_statements_info%20system%20view%20to%20show%20pg_stat_statements%20activity).

We'll need to [ignore this table](https://github.com/scenic-views/scenic/blob/main/lib/scenic/schema_dumper.rb#L33) I think.

**Comment by derekprior** [comment]
We rely on Rails' ignore list so we'd either have to override that or update the query we use to fetch views to ignore it. My preference is the latter.

https://github.com/scenic-views/scenic/blob/f3b8f732f195adbf0a8fab90a79a2c8b2b68f567/lib/scenic/adapters/postgres/views.rb#L25-L40

**Comment by calebhearth** [comment]
Ah I forgot that was a monkey patch for older versions of Rails.

**Comment by jwoodrow** [comment]
Any news on when this will get fixed ? I've been manually deleted these lines to fix this error for weeks now 😅

**Comment by calebhearth** [comment]
I’ll merge the fix later this morning. Thanks for the reminder.
