### ISSUE TITLE
New Rails/MigrationClassName cop has an issue with migration filename

### ISSUE THREAD

**Issue by schinery** [scenic-views/scenic#355]
There is a new auto correctable `Rails/MigrationClassName` cop for `rubocop-rails` that seems to have a problem with the migration filename ending in `_1`.

If I have a migration called `db/migrate/20211227122237_update_things_to_version_4.rb` I will get the following rubocop error when trying to auto correct it:

```sh
rubocop -A db/migrate/20211227122237_update_things_to_version_4.rb

Inspecting 1 file
C

Offenses:

db/migrate/20211227122237_update_things_to_version_4.rb:3:7: C: [Corrected] Rails/MigrationClassName: Replace with UpdateSubJobExportsToVersion4 that matches the file name.
class UpdateSubJobExportsToVersion4 < ActiveRecord::Migration[6.1]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 files inspected, 1 offense detected, 1 offense corrected
Infinite loop detected in /Users/me/my_app/db/migrate/20211227122237_update_things_to_version_4.rb and caused by Rails/MigrationClassName
```

Renaming the migration to `db/migrate/20211227122237_update_things_to_version4.rb` then the cop is satisfied that the filename is correct for the migration class name.

Is it possible to change the migration generator to output the files to end in `version{number}`?

**Comment by derekprior** [comment]
I'm not sure I agree that the file name we use today is incorrect. Are we sure the linter is correct?

**Comment by schinery** [comment]
Hey @derekprior, you’re right it actually was a rubocop-rails issue (https://github.com/rubocop/rubocop-rails/issues/667) which has now been resolved and awaiting release.

Sorry I didn’t check there first 😔
