### ISSUE TITLE
getting error Scenic::Adapters::Postgres::MaterializedViewsNotSupportedError 

### ISSUE THREAD

**Issue by yogeshbyjus** [scenic-views/scenic#358]
Sometimes the gem throws Scenic::Adapters::Postgres::MaterializedViewsNotSupportedError even though the aws rds has postgres version of 11.3 which supports materialized views. Anyone else facing similar issue?

Environment Details 
ruby '~> 2.6.6'
gem 'rails', '= 5.2.3'

**Comment by derekprior** [comment]
By default, Scenic relies on Rails' underlying database adapter to define `supports_materialized_views?`, which was a somewhat recent addition to Rails adapters. To compensate for the fact that older versions of Rails (and maybe some oddball adapters) don't define this method, we will do the check ourselves in those cases. We just check if `postgresql_version >= 90300`. 

I've received no other reports of an issue like this. My guess is you have a mismatch in versions you are using in development or are perhaps using a custom adapter that is doing something different. Either way, I don't have enough information to go on here. If you're able to provide a reproducible test case, we can look into it.
