### ISSUE TITLE
Sequences

### ISSUE THREAD

**Issue by brentgreeff** [scenic-views/scenic#363]
Would be great if this gem or some kind of fork allowed for managing sequences.

**Comment by derekprior** [comment]
I think there's certainly a useful pattern in this gem around versioned SQL files that could be used for many other things - sequences, functions, etc - but it goes beyond our intended scope.

It's possible we could extract the versioned SQL file parts of scenic to something that scenic and other gems could depend on. That's something @calebhearth and I have chatted about briefly for a long time. The fact that we haven't done it yet is a pretty good signal to its importance for us...
