### ISSUE TITLE
Is it possible to make it work with Sinatra or any other Rack app?

### ISSUE THREAD

**Issue by kirqe** [scenic-views/scenic#367]
The provided generator doesn't  seem to work.
Creating the migration and the view files manually and then running `rake db:migrate` leads to 

```
NameError: uninitialized constant Scenic::Adapters::Postgres::SimpleDelegator

      class Connection < SimpleDelegator
                         ^^^^^^^^^^^^^^^
```

**Comment by derekprior** [comment]
Possible? Probably. Right now there's a hard dependency on `railties` for initialization (and to link us to approved rails versions. I think we could make that a soft requirement somehow, and require folks who aren't using Rails to initialize Scenic appropriately. Having said that, my desire to do that is pretty low. This project has existed for years with very little call (any?) to do this.

The specific error above is only indirectly related to Rails. It seems that as of Ruby 2.7+, `SimpleDelegator` is not required by default and has to be required with `require "delegator"`. When running in rails, that require has already been run by the framework.

**Comment by kirqe** [comment]
I think I made it work by removing railties and replacing a couple of places with `Rails.join` and things like `indent(2)` and I load it in the Rakefile with `Scenic.load` :D 

Don't even need to require delegate 

Thanks
