### ISSUE TITLE
schema.rb diff after running migrations

### ISSUE THREAD

**Issue by kleinjm** [scenic-views/scenic#369]
Our team continuously sees a diff when running migrations. This diff can appear even when there are not pending migrations.

Example
```
-    WHERE ((orders.state)::text = ANY ((ARRAY['placed'::character varying, 'processing'::character varying, 'complete'::character varying])::text[]))
+    WHERE ((orders.state)::text = ANY (ARRAY[('placed'::character varying)::text, ('processing'::character varying)::text, ('complete'::character varying)::text]))
```

The changes seem to be between `[` and `(` and the addition/removal of `::text`. We don't run a containerized environment so differences between our local versions of postgres are possible but I'm unsure if that is the cause. Additionally, committing either version of this diff doesn't seem to have an effect other than the annoyance of causing others to generate the diff each time.

If you have any insights, please advise. Thank you!

**Comment by OskarsEzerins** [comment]
@kleinjm @derekprior I've replicated changing output by altering the PostgreSQL database's `lc_collate` and `lc_ctype` settings. When set to `C`, PostgreSQL casts each array element individually, whereas with `en_US.UTF-8`, it casts the entire array at once.

<details>
<summary>Steps to change these settings (PostgreSQL v14.12)</summary>

1. Create a new database with the desired locale settings:

   ```sql
   CREATE DATABASE new_db_name
   WITH TEMPLATE = template0
   ENCODING = 'UTF8'
   LC_COLLATE = 'C'
   LC_CTYPE = 'C';
   ```

2. Dump and restore the database:

   ```bash
   pg_dump your_db_name > your_db_name.sql
   psql new_db_name < your_db_name.sql
   ```

</details>

Further investigation is required, as these changes affect my dev environment, but another developer cannot reproduce the same output. This suggests other settings might also influence this behavior, potentially additional locale configurations. I haven't pinpointed the exact ones yet.

**Comment by derekprior** [comment]
Good find!
