### ISSUE TITLE
How to persist `'now'::timestamp` / prevent being computed with `rails db:migrate`

### ISSUE THREAD

**Issue by unRARed** [scenic-views/scenic#370]
We recently added `scenic` to our Rails apps so we could test some reporting. We really like this Gem, however, we are using `'now'::timestamp` in some of our SQL. While this can be run directly in Postgres, when we `rails db:migrate`, the value is computed in the view definition from `./db/schema.rb`... which is not we want. Does anyone know if this is a limitation of Postgres SQL Views, Rails internals or Scenic? 

this in some_file_v01.sql:
`re.created_at < ('now'::timestamp - '2 years'::interval)`
is being computed to this in db/schema.rb:
`re.created_at < ('2022-10-10 19:59:56.720342'::timestamp without time zone - 'P2Y'::interval)`

**Comment by fatkodima** [comment]
Seems like you really should use a solution similar to https://stackoverflow.com/questions/69818868/now-change-to-static-timestamp-after-creating-view-in-postgresql.

**Comment by derekprior** [comment]
`localtimestamp` is what you want

**Comment by unRARed** [comment]
Thank  you!
