### ISSUE TITLE
add a support for pg_ivm ?

### ISSUE THREAD

**Issue by buncis** [scenic-views/scenic#377]
https://github.com/sraoss/pg_ivm

> Incremental View Maintenance (IVM) is a way to make materialized views up-to-date in which only incremental changes are computed and applied on views rather than recomputing the contents from scratch as REFRESH MATERIALIZED VIEW does. IVM can update materialized views more efficiently than recomputation when only small parts of the view are changed.

I think I could make it work for my own fork, but its better to merged, but I never make a big pull request before, never write a test

willing to do it though just need a guidance

**Comment by derekprior** [comment]
my gut reaction here is that it would likely be best for pg_ivm support to be created in a custom adapter that inherits from our Postgres adapter and overrides the necessary materialized view schema methods.

We only maintain the Postgres adapter but there are several other gems (see README) that implement adapters of their own. I'd suggest this path to start.
