### ISSUE TITLE
Add support for a cache_key and/or cache_version

### ISSUE THREAD

**Issue by thefotios** [scenic-views/scenic#389]
As a user
I want to define custom caching methods (see [ActiveRecord::Relation.cache_key](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/relation.rb#L336-L339))
So that it can be used transparently in `Rails.cache` (and other places that rely on it to be "cacheable")
And so that cache logic can be consolidated in a single, opinionated source of truth

---

I recently came across a case where we had a view that was aggregating events. The view is somewhat complex, but with knowledge of the inner workings, we know that the data doesn't change if the events haven't changed. Also, IMHO views don't typically include an `updated_at`, so the standard approach of using `count` and `max(:updated_at)` don't really make sense. It would be great if the model could essentially delegate it's cache key so that consumers could cache it without potentially running an expensive view and having to know the best way to cache the data. A cursory search shows [another library](https://github.com/cmer/scope_cache_key) did something similar for scopes which could act as a starting point.

For example
```ruby
class User < ApplicationRecord
  has_many :hats
  has_many :special_hats
end

class Hat < ApplicationRecord
  belongs_to :user
end

# This is the view backed model
class SpecialHat < ApplicationRecord
   # select * from hats where ....... something really expensive
  def read_only? = true
  
  belongs_to :user

  # Some sort of method that lets us delegate to something else that responds to `cache_key|version`
  cache_with { user.hats }
end
```

**Comment by derekprior** [comment]
This seems like something you can do yourself by overriding `cache_key` or `collection_cache_key` as appropriate? I'm not sure what benefit scenic providing a DSL would have.
