### ISSUE TITLE
Cannot replace materialized views

### ISSUE THREAD

**Issue by sleepywei** [scenic-views/scenic#393]
I have a materialized view, and I tried to update it:
```bash
rails g scenic:view my_view --materialized
```
However, I got the following error: 
`ERROR:  canceling statement due to statement timeout`

Then, I tried:
```bash
rails g scenic:view my_view --materialized --replace
```

Got error:
`ArgumentError: Cannot replace materialized views`

According to the README, seems the `--replace` should be able to handle the materialized views. I'm confused. Any suggestion?

Thanks in advance.

**Comment by derekprior** [comment]
I'm not sure what the cause of your first error is. You got that right when you ran the generator?

The error you are getting in the second case is correct. PG does not support `OR REPLACE` on materialized views. We should clarify on the README.

**Comment by derekprior** [comment]
Updated the docs: https://github.com/scenic-views/scenic#what-if-i-want-to-change-a-view-without-dropping-it
