### ISSUE TITLE
Feature Request: Support Generated Columns

### ISSUE THREAD

**Issue by nicosuave** [scenic-views/scenic#400]
Both [Postgres](https://www.postgresql.org/docs/current/ddl-generated-columns.html) and [MySQL](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html) have generated columns, which face similar versioning issues to views and would benefit under Scenic version management.

**Comment by derekprior** [comment]
This isn't something we're going to support directly in Scenic. I do think the general pattern of file-based versioning we're using is more broadly applicable (see also https://github.com/teoljungberg/fx) but implementing the pattern for all the database things is not something in scope for us.
