### ISSUE TITLE
Default to latest view definition for create_view

### ISSUE THREAD

**Issue by heatherbooker** [scenic-views/scenic#404]
Hello and thanks for sharing this very useful gem.

I am looking at running a migration that looks like:

```rb
def up
  drop_view a
  drop_view b
  drop_view c
   ...etc, 15-20 of them
  drop_view z_which_is_used_by_all_the_other_views

  do_what_i_actually_wanna_do_which_is_change_column_type_of_a_table_that_view_z_depends_on
end

def down
  create_view a
  create_view b
  create_view c
   ...etc
```

a, b, c, etc - all my views are defined in db/views/a_v03.sql, db/views/b_v07.sql, etc - there are many versions of each.
It seems that `create_view a` uses the first definition (`_v01.sql`) by default, unless I specify the latest version like

```rb
create_view a, version: 3
```

Is there a way to automatically use the latest version of a view, when running `create_view`?

**Comment by derekprior** [comment]
This would violate one of the aims of scenic which is to provide versioned changes to views. Defaulting to the first version is okay because it's the first version whether you run it today or three years from now. That would not be true for defaulting to the latest version as that would change depending on when the migration is run.

**Comment by onesneakymofo** [comment]
@heatherbooker I came here looking for this as well as I had to convert a datetime to a date on a column, but that column was used in a few of my views.  

I disagree with @derekprior as there are some edge cases where it is needed like mine above.  I feel like defaulting to the first is fine, but if you provide a `version: :latest` key-value, it should grab the last version that was created.

For me, I did this programatically basing it off of the file name:

```ruby
    views.each do |view|
      version = Dir.glob("db/views/#{view}_v*.sql").map { |f| f[/v(\d+)\.sql$/, 1].to_i }.max
      create_view view, version: version
    end
 ```

**Comment by derekprior** [comment]
> I disagree with @derekprior as there are some edge cases where it is needed like mine above. 

To be clear, I was offering a fact, not an opinion. `:latest` can change depending on when the migration is run which can lead to ambiguous view versioning during rollbacks, in development among a team, etc.

I think that's worth keeping over adding `:latest`, which I'd never use myself and consider an anti-pattern. If I found myself in the painful situation you're in I'd likely use code _similar_ to what you wrote to identify the current versions at migration runtime and then bake those into the migration itself.

If we were to make a feature change here, I'd sooner consider something that automatically drops and recreates dependencies of modified tables and views. This would be a combination similar to index reapplication and cascading refreshes that we offer on materialized views.

That said, I'm personally unlikely to prioritize that. If you want to kick the tires on something like that, I'd consider it if it were robust.
